---
name: wtf-go

services:
  backend:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD", "wtf-go", "healthcheck"]
    volumes:
      - ./config.yaml:/etc/wtf-go/config.yaml:ro
  swagger:
    image: swaggerapi/swagger-ui:v5.32.0@sha256:641afb45f0f14167da03659c220eff40c5aab231337ed2bad494802737d4e2ae
    restart: always
    environment:
      - SWAGGER_JSON=/opt/swagger.yaml
      - VALIDATOR_URL=none
    volumes:
      - ../../api/openapi.yaml:/opt/swagger.yaml
    ports:
      - 8082:8080
    healthcheck:
      test: wget -S --spider http://127.0.0.1:8080 -U local-healthcheck
