---
name: wtf-go

services:
  backend:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD", "wtf-go", "healthcheck"]
    volumes:
      - ./config.yaml:/etc/wtf-go/config.yaml:ro
  swagger:
    image: swaggerapi/swagger-ui:v5.32.1@sha256:74e37eb854b2cec5a8bcfdc4b0604a0354fbbf7209b68c3357d3221286bcb1dc
    restart: always
    environment:
      - SWAGGER_JSON=/opt/swagger.yaml
      - VALIDATOR_URL=none
    volumes:
      - ../../api/openapi.yaml:/opt/swagger.yaml
    ports:
      - 8082:8080
    healthcheck:
      test: wget -S --spider http://127.0.0.1:8080 -U local-healthcheck
