image: alpine/3.23
oauth: pages.sr.ht/PAGES:RW
packages:
  - docker
  - hut
tasks:
  - init-docker: |
      sudo service docker start
      sudo addgroup ${USER} docker
  - install-golang: |
      cd /tmp
      curl -O -sSfL https://go.dev/dl/go1.26.0.linux-amd64.tar.gz
      [ "$(sha256sum go1.26.0.linux-amd64.tar.gz | cut -d ' ' -f 1)" == "aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235" ]
      sudo tar -C /usr/local -xzf go1.26.0.linux-amd64.tar.gz
      sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
      sudo ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt
  - install-golangci-lint: |
      cd /tmp
      curl -O -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.10.1/golangci-lint-2.10.1-linux-amd64.tar.gz
      [ "$(sha256sum golangci-lint-2.10.1-linux-amd64.tar.gz | cut -d ' ' -f 1)" == "dfa775874cf0561b404a02a8f4481fc69b28091da95aa697259820d429b09c99" ]
      sudo tar -xzf golangci-lint-2.10.1-linux-amd64.tar.gz -C /usr/local/bin --strip-components 1 golangci-lint-2.10.1-linux-amd64/golangci-lint
  - install-romero: |
      docker pull ne02ptzero/romero
  - go-modules: |
      cd wtf-go
      go mod tidy -diff
  - go-test: |
      cd wtf-go
      go test -v ./...
  - linting: |
      cd wtf-go
      golangci-lint run ./...
  - docker-build: |
      cd wtf-go
      docker build --file ./build/Dockerfile .
  - doc-build: |
      docker run --rm -v "$(pwd)/wtf-go:/wtf-go" -w /wtf-go/docs ne02ptzero/romero:latest build
      cd wtf-go/docs/book
      tar -czvf ../book.tar.gz .
  - doc-deploy: |
      if [[ $GIT_REF != refs/heads/main ]]; then
        echo "Only deploy documentation on the main branch."
        echo "Current branch: ${GIT_REF}"
        exit 0
      fi
      hut pages publish \
        --domain lvjp.srht.site \
        --subdirectory wtf-go \
        wtf-go/docs/book.tar.gz
