version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - errname
    - exhaustive
    - fatcontext
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - govet
    - iface
    - importas
    - ineffassign
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - reassign
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      check-type-assertions: true
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
      check-blank: true
    gocyclo:
      # minimal code complexity to report, 30 by default
      min-complexity: 15
    gosec:
      excludes:
        - G704 # Broken: https://github.com/securego/gosec/pull/1522
        - G705 # Broken: https://github.com/securego/gosec/pull/1522
    govet:
      enable:
        # Check for redundant or impossible nil comparisons.
        - nilness
        # Check for possible unintended shadowing of variables.
        - shadow
    revive:
      rules:
        - name: package-comments
          disabled: true
    wrapcheck:
      ignore-package-globs:
        # Ignore our local modules, as they have a lot of places where errors are not wrapped, and it's not worth the effort to fix them.
        - github.com/lvjp/wtf-go/*
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Needed till this issue is not resolved: https://github.com/Antonboom/testifylint/issues/307
      - path: pkg/auth/token/store_memory_test\.go
        text: "require-error: for error assertions use require"
        linters:
          - testifylint
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: strict
