[book]
title = "wtf-go documentation"
authors = ["Laurent VERDOÏA"]
language = "en"

[output.html]
site-url = "/wtf-go/"
git-repository-url = "https://github.com/lvjp/wtf-go"
edit-url-template = "https://github.com/lvjp/wtf-go/edit/main/docs/src/{{ . }}"
source-url-template = "https://github.com/lvjp/wtf-go/blob/main/docs/src/{{ .Path }}#L{{ .Start }}-{{ .End }}"
