---
name: "CI"

on:
  push:

# Disable all default permissions
permissions: {}

jobs:
  go:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - run: go mod download -x

      - run: go mod tidy -diff

      - name: Unit tests
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11.4 # renovate: datasource=github-releases depName=golangci/golangci-lint
          skip-cache: true

      - name: Docker build
        run: docker compose build backend
        working-directory: ./deployments/local

      - name: Deploy local test cluster
        run: docker compose up --detach --wait
        working-directory: ./deployments/local

      - name: Run integration tests
        run: go test -v ./tests/e2e/...
        env:
          TEST_WTF_GO_BACKEND_ENDPOINT: http://localhost:8081

  documentation:
    runs-on: ubuntu-24.04

    permissions:
      contents: read # to checkout the source code

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build the book
        run: docker run --rm --volume "$(pwd):/wtf-go" --workdir /wtf-go/docs ne02ptzero/romero:latest build

      - name: Generate GitHub Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./docs/book

  deploy:
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      id-token: write # to verify the deployment originates from an appropriate source
      pages: write # to deploy to Pages

    needs:
      - documentation

    steps:
      - name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
